name: prepdesk
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.4
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/java_mcqs.json
    - assets/cloud_computing_mcqs.json


  
flutter_launcher_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/images/logo.png"